# Generated by Django 5.2 on 2025-04-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='موجود است')),
                ('descroption', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('off', models.IntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('count', models.IntegerField(verbose_name='تعداد موجودی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
