# Generated by Django 5.2 on 2025-06-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, verbose_name='رنگ')),
                ('hex_code', models.CharField(max_length=200, verbose_name='کد رنگی')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='دسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='موجود است')),
                ('descroption', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('off', models.IntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('count', models.IntegerField(verbose_name='تعداد موجودی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ('color', models.ManyToManyField(to='product_app.product_color')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.productcategory')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
