# Generated by Django 5.2 on 2025-05-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, null=True),
        ),
    ]
