# Generated by Django 5.2 on 2025-05-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_list_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True),
        ),
    ]
