# Generated by Django 5.2 on 2025-05-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_product_color_alter_productcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='color',
            field=models.ManyToManyField(to='product_app.product_color'),
        ),
    ]
