# Generated by Django 5.2 on 2025-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(default='خبر بدون عنوان', max_length=200, verbose_name='نام خبر')),
                ('user', models.CharField(max_length=200, verbose_name='نام کاربر')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریح انتشار')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='ساعت انتشار')),
                ('news', models.CharField(max_length=400, verbose_name='اخبار ما')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
