# Generated by Django 5.2 on 2025-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_name',
            field=models.CharField(default='خبر بدون عنوان', max_length=200, verbose_name='نام خبر'),
        ),
    ]
