# Generated by Django 5.2 on 2025-06-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='اضافه کردن عکس خبر'),
        ),
    ]
