# Generated by Django 5.2 on 2025-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=200, verbose_name='ادرس ایمیل')),
                ('subject', models.CharField(max_length=300, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ پیام')),
            ],
        ),
    ]
